# SMTP Configuration for email sending
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USERNAME = "skipassmyholidaylivigno@gmail.com"
SMTP_PASSWORD = "viasaroch1686"
SMTP_FROM_EMAIL = "info@myholidaylivigno.com"
